name: Check python module

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_python_module:
    name: Check python module
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", 3.13, 3.14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: ni/python-actions/setup-python@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
      - name: Analyze Python Project
        uses: ni/python-actions/analyze-project@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
        with:
          install-args: "--with test --with lint --all-extras"
      - name: Bandit security checks
        run: poetry run bandit -c pyproject.toml -r src/nitlsconfig
