name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_python_module:
    name: Check python module
    uses: ./.github/workflows/check_module.yml
  check_docs:
    name: Check docs
    uses: ./.github/workflows/check_docs.yml
  checks_succeeded:
    name: Checks succeeded
    needs: [check_python_module, check_docs]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  run_unit_tests:
    name: Run unit tests
    uses: ./.github/workflows/run_unit_tests.yml
    needs: [checks_succeeded]